import type { InstructionLanguage } from './types';

const ru = {
  paymentPending: 'Платёж обрабатывается. Доступ появится после подтверждения Lemon Squeezy.', required: 'Пожалуйста, введите e-mail и пароль.', loginSuccess: 'Успешный вход в аккаунт!', verifyAfterLogin: 'Вход выполнен. Подтвердите e-mail по ссылке из письма.', checkoutUnavailable: 'Оплата временно недоступна. Попробуйте позже.', portalUnavailable: 'Управление подпиской временно недоступно.',
  profileTitle: 'Личный кабинет ученика', loginTitle: 'Вход в аккаунт', resetTitle: 'Восстановление пароля', registerTitle: 'Регистрация ученика', subtitle: 'Сохранение прогресса и доступ к урокам', close: 'Закрыть окно аккаунта', checking: 'Проверка аккаунта…', account: 'Учётная запись', emailVerification: 'Подтверждение e-mail', verified: 'Подтверждён', unverified: 'Не подтверждён', subscriptionStatus: 'Статус подписки',
  verifyTitle: 'Подтвердите e-mail', verifyBody: 'Перейдите по ссылке в письме от Firebase. После подтверждения вернитесь сюда и обновите статус.', resend: 'Отправить письмо повторно', refresh: 'Я подтвердил e-mail', premiumTitle: 'Полный доступ ко всем урокам', premiumBody: 'Подписка включает неограниченный доступ ко всем интерактивным урокам венгерского языка, озвучке слов и аудиотренажёрам.', organizationActive: 'Premium предоставлен организацией', organizationInactive: 'Организационный доступ не активен', until: 'до {date}', adminAccess: 'Доступ предоставлен администратором', loading: 'Загрузка…', manage: 'Управлять подпиской', chooseTerm: 'Выберите срок подписки', verifyToSubscribe: 'Подтвердите e-mail, чтобы оформить подписку.', charge: 'Списание {price} {period}. Все тарифы включают одинаковый Premium-доступ.', processing: 'Обработка…', buy: 'Оформить за {price}',
  organizationCodeTitle: 'У меня есть код организации', organizationCodeBody: 'Код активируется один раз и закрепляет свободное место за вашим аккаунтом.', activate: 'Активировать', deleteAccount: 'Удалить аккаунт', logout: 'Выйти из аккаунта', deleteTitle: 'Безвозвратное удаление аккаунта', deleteLead: 'Будут удалены:', deleteItems: ['учётная запись Firebase Auth и профиль;', 'прогресс, результаты заданий, настройки и review cards;', 'entitlement и связь с Premium-доступом; организационное место будет освобождено без повторной активации использованного ключа;', 'локальный кэш учебного прогресса на этом устройстве.'], retention: 'Минимальные записи о платежах и webhook-событиях могут храниться для бухгалтерских, налоговых, возвратных и юридических обязательств. Прямая связь сохранённой записи с Firebase UID удаляется.', cancelFirst: 'Сначала отмените активную подписку, чтобы исключить будущие списания.', openPortal: 'Открыть Customer Portal', currentPassword: 'Текущий пароль', deletionConsent: 'Я понимаю, что данные и оставшийся Premium-доступ нельзя будет восстановить.', deleteForever: 'Удалить безвозвратно',
  loginTab: 'Вход', registerTab: 'Регистрация', email: 'Электронная почта (e-mail)', password: 'Пароль', forgot: 'Забыли пароль?', signIn: 'Войти в систему', resetHelp: 'Введите e-mail аккаунта. Firebase отправит ссылку, по которой можно установить новый пароль.', sendReset: 'Отправить ссылку для сброса', backToLogin: 'Вернуться ко входу', yourEmail: 'Ваш e-mail', createPassword: 'Придумайте пароль (минимум 6 символов)', repeatPassword: 'Повторите пароль', register: 'Зарегистрироваться и начать учёбу',
};
export type AuthCopy = typeof ru;

const en: AuthCopy = {
  paymentPending: 'Your payment is being processed. Access will appear after Lemon Squeezy confirms it.', required: 'Enter your email and password.', loginSuccess: 'Signed in successfully!', verifyAfterLogin: 'You are signed in. Confirm your email using the link we sent.', checkoutUnavailable: 'Checkout is temporarily unavailable. Try again later.', portalUnavailable: 'Subscription management is temporarily unavailable.',
  profileTitle: 'Student account', loginTitle: 'Sign in', resetTitle: 'Reset password', registerTitle: 'Create student account', subtitle: 'Save your progress and access lessons', close: 'Close account window', checking: 'Checking account…', account: 'Account', emailVerification: 'Email verification', verified: 'Verified', unverified: 'Not verified', subscriptionStatus: 'Subscription status',
  verifyTitle: 'Confirm your email', verifyBody: 'Open the link in the Firebase email. Then return here and refresh the status.', resend: 'Send the email again', refresh: 'I confirmed my email', premiumTitle: 'Full access to every lesson', premiumBody: 'The subscription includes unlimited access to all interactive Hungarian lessons, word recordings, and audio practice.', organizationActive: 'Premium provided by your organization', organizationInactive: 'Organization access is inactive', until: 'until {date}', adminAccess: 'Access granted by an administrator', loading: 'Loading…', manage: 'Manage subscription', chooseTerm: 'Choose a subscription period', verifyToSubscribe: 'Confirm your email before subscribing.', charge: 'You will be charged {price} {period}. Every plan includes the same Premium access.', processing: 'Processing…', buy: 'Subscribe for {price}',
  organizationCodeTitle: 'I have an organization code', organizationCodeBody: 'A code can be activated once and assigns an available seat to your account.', activate: 'Activate', deleteAccount: 'Delete account', logout: 'Sign out', deleteTitle: 'Permanently delete account', deleteLead: 'The following will be deleted:', deleteItems: ['your Firebase Auth account and profile;', 'progress, activity results, settings, and review cards;', 'your entitlement and Premium access link; an organization seat will be released without reactivating the used code;', 'the local learning progress cache on this device.'], retention: 'Minimal payment and webhook records may be retained for accounting, tax, refund, and legal obligations. The direct link between retained records and your Firebase UID is removed.', cancelFirst: 'Cancel your active subscription first to prevent future charges.', openPortal: 'Open Customer Portal', currentPassword: 'Current password', deletionConsent: 'I understand that my data and remaining Premium access cannot be restored.', deleteForever: 'Delete permanently',
  loginTab: 'Sign in', registerTab: 'Register', email: 'Email address', password: 'Password', forgot: 'Forgot password?', signIn: 'Sign in', resetHelp: 'Enter your account email. Firebase will send a link that lets you set a new password.', sendReset: 'Send reset link', backToLogin: 'Back to sign in', yourEmail: 'Your email', createPassword: 'Create a password (at least 6 characters)', repeatPassword: 'Repeat password', register: 'Register and start learning',
};

const es: AuthCopy = {
  paymentPending: 'Tu pago se está procesando. El acceso aparecerá cuando Lemon Squeezy lo confirme.', required: 'Introduce tu correo electrónico y contraseña.', loginSuccess: 'Has iniciado sesión correctamente.', verifyAfterLogin: 'Has iniciado sesión. Confirma tu correo mediante el enlace enviado.', checkoutUnavailable: 'El pago no está disponible temporalmente. Inténtalo más tarde.', portalUnavailable: 'La gestión de la suscripción no está disponible temporalmente.',
  profileTitle: 'Cuenta del estudiante', loginTitle: 'Iniciar sesión', resetTitle: 'Restablecer contraseña', registerTitle: 'Crear cuenta de estudiante', subtitle: 'Guarda tu progreso y accede a las lecciones', close: 'Cerrar la ventana de la cuenta', checking: 'Comprobando la cuenta…', account: 'Cuenta', emailVerification: 'Verificación del correo', verified: 'Verificado', unverified: 'Sin verificar', subscriptionStatus: 'Estado de la suscripción',
  verifyTitle: 'Confirma tu correo', verifyBody: 'Abre el enlace del mensaje de Firebase. Después vuelve aquí y actualiza el estado.', resend: 'Volver a enviar el mensaje', refresh: 'Ya confirmé mi correo', premiumTitle: 'Acceso completo a todas las lecciones', premiumBody: 'La suscripción incluye acceso ilimitado a todas las lecciones interactivas de húngaro, grabaciones de palabras y prácticas de audio.', organizationActive: 'Premium proporcionado por tu organización', organizationInactive: 'El acceso de la organización está inactivo', until: 'hasta {date}', adminAccess: 'Acceso concedido por un administrador', loading: 'Cargando…', manage: 'Gestionar suscripción', chooseTerm: 'Elige la duración de la suscripción', verifyToSubscribe: 'Confirma tu correo antes de suscribirte.', charge: 'Se cobrarán {price} {period}. Todos los planes incluyen el mismo acceso Premium.', processing: 'Procesando…', buy: 'Suscribirse por {price}',
  organizationCodeTitle: 'Tengo un código de organización', organizationCodeBody: 'El código se activa una vez y asigna una plaza libre a tu cuenta.', activate: 'Activar', deleteAccount: 'Eliminar cuenta', logout: 'Cerrar sesión', deleteTitle: 'Eliminar la cuenta definitivamente', deleteLead: 'Se eliminarán:', deleteItems: ['la cuenta de Firebase Auth y el perfil;', 'el progreso, los resultados, los ajustes y las tarjetas de repaso;', 'el entitlement y la relación con el acceso Premium; se liberará la plaza de la organización sin reactivar el código usado;', 'la caché local del progreso de aprendizaje de este dispositivo.'], retention: 'Puede conservarse un registro mínimo de pagos y eventos webhook por obligaciones contables, fiscales, de reembolso y legales. Se elimina la relación directa entre esos registros y tu Firebase UID.', cancelFirst: 'Cancela primero la suscripción activa para evitar futuros cobros.', openPortal: 'Abrir Customer Portal', currentPassword: 'Contraseña actual', deletionConsent: 'Entiendo que mis datos y el acceso Premium restante no se podrán recuperar.', deleteForever: 'Eliminar definitivamente',
  loginTab: 'Entrar', registerTab: 'Registrarse', email: 'Correo electrónico', password: 'Contraseña', forgot: '¿Has olvidado la contraseña?', signIn: 'Iniciar sesión', resetHelp: 'Introduce el correo de tu cuenta. Firebase enviará un enlace para establecer una contraseña nueva.', sendReset: 'Enviar enlace de restablecimiento', backToLogin: 'Volver al inicio de sesión', yourEmail: 'Tu correo', createPassword: 'Crea una contraseña (mínimo 6 caracteres)', repeatPassword: 'Repite la contraseña', register: 'Registrarse y empezar a aprender',
};

export const AUTH_COPY: Record<InstructionLanguage, AuthCopy> = { ru, en, es };

export function formatAuthCopy(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template);
}

const ACCOUNT_MESSAGES: Record<Exclude<InstructionLanguage, 'ru'>, Record<string, string>> = {
  en: {
    'Неверный e-mail или пароль.': 'Incorrect email or password.', 'Аккаунт с этим e-mail уже существует. Войдите с вашим паролем.': 'An account with this email already exists. Sign in with your password.', 'Проверьте правильность e-mail.': 'Check the email address.', 'Пароль должен содержать минимум 6 символов.': 'The password must contain at least 6 characters.', 'Слишком много попыток. Попробуйте позже.': 'Too many attempts. Try again later.', 'Ошибка сети. Проверьте подключение и повторите попытку.': 'Network error. Check your connection and try again.', 'Заполните e-mail, пароль и подтверждение пароля.': 'Enter your email, password, and password confirmation.', 'Пароли не совпадают.': 'The passwords do not match.', 'Введите e-mail, указанный при регистрации.': 'Enter the email used for registration.', 'Аккаунт создан. Мы отправили письмо для подтверждения e-mail.': 'Account created. We sent an email confirmation link.', 'Аккаунт создан, но письмо не отправилось. Отправьте его повторно из личного кабинета.': 'Account created, but the confirmation email could not be sent. Send it again from your account.', 'Не удалось зарегистрироваться.': 'Registration failed.', 'Успешный вход': 'Signed in successfully.', 'Не удалось войти.': 'Sign-in failed.', 'Войдите в аккаунт повторно.': 'Sign in again.', 'Введите текущий пароль.': 'Enter your current password.', 'Аккаунт и учебные данные удалены.': 'Your account and learning data were deleted.', 'Не удалось удалить аккаунт. Попробуйте позже.': 'Could not delete the account. Try again later.', 'Код активирован. Организационный Premium-доступ подключён.': 'Code activated. Organization Premium access is now enabled.', 'Не удалось активировать код организации.': 'Could not activate the organization code.', 'Если аккаунт с таким e-mail существует, Firebase отправит письмо для установки нового пароля.': 'If an account with this email exists, Firebase will send a password reset message.', 'Новое письмо для подтверждения отправлено.': 'A new confirmation email was sent.', 'E-mail уже подтверждён.': 'The email is already verified.', 'E-mail подтверждён.': 'Email verified.', 'E-mail пока не подтверждён. Перейдите по ссылке из письма.': 'The email is not verified yet. Open the link in the message.', 'Не удалось отправить письмо. Попробуйте позже.': 'Could not send the email. Try again later.',
  },
  es: {
    'Неверный e-mail или пароль.': 'Correo o contraseña incorrectos.', 'Аккаунт с этим e-mail уже существует. Войдите с вашим паролем.': 'Ya existe una cuenta con este correo. Inicia sesión con tu contraseña.', 'Проверьте правильность e-mail.': 'Comprueba el correo electrónico.', 'Пароль должен содержать минимум 6 символов.': 'La contraseña debe tener al menos 6 caracteres.', 'Слишком много попыток. Попробуйте позже.': 'Demasiados intentos. Inténtalo más tarde.', 'Ошибка сети. Проверьте подключение и повторите попытку.': 'Error de red. Comprueba la conexión e inténtalo de nuevo.', 'Заполните e-mail, пароль и подтверждение пароля.': 'Introduce el correo, la contraseña y su confirmación.', 'Пароли не совпадают.': 'Las contraseñas no coinciden.', 'Введите e-mail, указанный при регистрации.': 'Introduce el correo usado para registrarte.', 'Аккаунт создан. Мы отправили письмо для подтверждения e-mail.': 'Cuenta creada. Hemos enviado un enlace para confirmar el correo.', 'Аккаунт создан, но письмо не отправилось. Отправьте его повторно из личного кабинета.': 'La cuenta se creó, pero no se pudo enviar el mensaje. Vuelve a enviarlo desde tu cuenta.', 'Не удалось зарегистрироваться.': 'No se pudo completar el registro.', 'Успешный вход': 'Has iniciado sesión correctamente.', 'Не удалось войти.': 'No se pudo iniciar sesión.', 'Войдите в аккаунт повторно.': 'Vuelve a iniciar sesión.', 'Введите текущий пароль.': 'Introduce tu contraseña actual.', 'Аккаунт и учебные данные удалены.': 'La cuenta y los datos de aprendizaje se han eliminado.', 'Не удалось удалить аккаунт. Попробуйте позже.': 'No se pudo eliminar la cuenta. Inténtalo más tarde.', 'Код активирован. Организационный Premium-доступ подключён.': 'Código activado. El acceso Premium de la organización está habilitado.', 'Не удалось активировать код организации.': 'No se pudo activar el código de la organización.', 'Если аккаунт с таким e-mail существует, Firebase отправит письмо для установки нового пароля.': 'Si existe una cuenta con este correo, Firebase enviará un mensaje para restablecer la contraseña.', 'Новое письмо для подтверждения отправлено.': 'Se ha enviado un nuevo mensaje de confirmación.', 'E-mail уже подтверждён.': 'El correo ya está verificado.', 'E-mail подтверждён.': 'Correo verificado.', 'E-mail пока не подтверждён. Перейдите по ссылке из письма.': 'El correo aún no está verificado. Abre el enlace del mensaje.', 'Не удалось отправить письмо. Попробуйте позже.': 'No se pudo enviar el mensaje. Inténtalo más tarde.',
  },
};

export function localizeAccountMessage(message: string, language: InstructionLanguage): string {
  if (language === 'ru' || !/[А-Яа-яЁё]/u.test(message)) return message;
  return ACCOUNT_MESSAGES[language][message] ?? (language === 'en' ? 'The operation could not be completed. Try again.' : 'No se pudo completar la operación. Inténtalo de nuevo.');
}
