import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { LESSON_18 } from '../src/data/lessons/lesson18';
import { LESSONS_META } from '../src/data/lessons/index';
import { LESSON_TRANSLATION_MAP } from '../src/data/lessonTranslations';
const es=JSON.parse(readFileSync(new URL('../src/i18n/lessonTranslations.es.json',import.meta.url),'utf8')) as Record<string,string>;
const pub=JSON.parse(readFileSync(new URL('../src/i18n/lessonTranslations.public.es.json',import.meta.url),'utf8')) as Record<string,string>;
const SKIP=new Set(['id','activityId','objectiveId','assetId','audioText','baseWord','cardId','hu','ipa','lexemeId','phonetic','targetPhonetic']);
function keys(v:unknown,f='',r=new Set<string>()):Set<string>{if(typeof v==='string'){if(SKIP.has(f))return r;for(const p of v.split(/(<[^>]+>)/gu)){const k=p.startsWith('<')?'':p.trim();if(/[А-Яа-яЁё]/u.test(k))r.add(k)}return r}if(Array.isArray(v))v.forEach(x=>keys(x,f,r));else if(v&&typeof v==='object')Object.entries(v).forEach(([k,x])=>keys(x,k,r));return r}
const lessonKeys=keys([LESSON_18,LESSONS_META.find(x=>x.number===18),LESSON_TRANSLATION_MAP[18]]);

test('Lesson 18 has complete Spanish coverage and a synchronized public subset',()=>{assert.equal(lessonKeys.size,467);const publicKeys=[...lessonKeys].filter(k=>k in pub);assert.equal(publicKeys.length,32);for(const k of lessonKeys){assert.ok(k in es,`missing full Spanish translation: ${k}`);assert.doesNotMatch(es[k],/[А-Яа-яЁё]/u,k)}for(const k of publicKeys)assert.equal(pub[k],es[k],k)});

test('Lesson 18 Spanish contains no known machine-translation residue',()=>{const forbidden=/Infinitación|Basic infinitive|\bcook\b|lugar \/ rublo|Deseo político|Construcciones modulares|dos pasillos|\bhelper\b|AUDITIZACIÓN|primer altavoz|destierro|posamente|trabajo de escritura de código abierto|Bloqueo político|\b(?:OPTIONAL SPEAKING|model answer|modalize|Destinguido)\b|\bperdonado\b/iu;const failures=[...lessonKeys].map(k=>[k,es[k]]as const).filter(([,v])=>forbidden.test(v));assert.deepEqual(failures,[])});

test('Lesson 18 Spanish preserves the modal and assessment distinctions',()=>{assert.match(es['С kell есть два полезных шаблона: общий безличный и личный. На A2 продуктивно тренируем прежде всего 1-е, 2-е и 3-е лицо единственного числа.'],/impersonal general.*personal.*primera, segunda y tercera persona del singular/u);assert.match(es['Не заменяй tud и lehet друг другом только потому, что по-русски оба иногда переводятся словом «можно / могу».'],/Tud expresa.*capacidad personal.*lehet \+ infinitivo.*posibilidad o permiso/u);assert.match(es['szeretnék здесь учим как готовую частотную форму для вежливого желания и просьбы. Полная система условного наклонения будет только в Lesson 23.'],/szeretnék.*deseo o petición cortés.*condicional.*lección 23/u);assert.match(es['Финальная типичная ошибка: nem kell = «не обязательно», а nem szabad = «запрещено». Эти функции нельзя менять местами.'],/nem kell.*no es obligatorio.*nem szabad.*está prohibido.*no son intercambiables/u);assert.match(es['В сценарии 15 ходов, из них 7 реплик ученика. RolePlay остаётся PARTIAL evidence: открытый ответ нельзя честно оценить полностью автоматически.'],/15 turnos.*7.*evidencia PARCIAL.*no puede evaluarse.*por completo/u);assert.equal(es['УРОК 18 · 7/11 · АУДИРОВАНИЕ'],'LECCIÓN 18 · 7/11 · COMPRENSIÓN AUDITIVA');assert.equal(es['УРОК 18 · 9/11 · ПИСЬМО'],'LECCIÓN 18 · 9/11 · ESCRITURA');assert.equal(es['УРОК 18 · 10/11 · OPTIONAL SPEAKING'],'LECCIÓN 18 · 10/11 · PRÁCTICA ORAL OPCIONAL')});
