import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { LESSON_15 } from '../src/data/lessons/lesson15';
import { LESSONS_META } from '../src/data/lessons/index';
import { LESSON_TRANSLATION_MAP } from '../src/data/lessonTranslations';
const es=JSON.parse(readFileSync(new URL('../src/i18n/lessonTranslations.es.json',import.meta.url),'utf8')) as Record<string,string>;
const pub=JSON.parse(readFileSync(new URL('../src/i18n/lessonTranslations.public.es.json',import.meta.url),'utf8')) as Record<string,string>;
const SKIP=new Set(['id','activityId','objectiveId','assetId','audioText','baseWord','cardId','hu','ipa','lexemeId','phonetic','targetPhonetic']);
function keys(v:unknown,f='',r=new Set<string>()):Set<string>{if(typeof v==='string'){if(SKIP.has(f))return r;for(const p of v.split(/(<[^>]+>)/gu)){const k=p.startsWith('<')?'':p.trim();if(/[А-Яа-яЁё]/u.test(k))r.add(k)}return r}if(Array.isArray(v))v.forEach(x=>keys(x,f,r));else if(v&&typeof v==='object')Object.entries(v).forEach(([k,x])=>keys(x,k,r));return r}
const lessonKeys=keys([LESSON_15,LESSONS_META.find(x=>x.number===15),LESSON_TRANSLATION_MAP[15]]);
test('Lesson 15 has complete Spanish coverage and a synchronized public subset',()=>{assert.equal(lessonKeys.size,492);const publicKeys=[...lessonKeys].filter(k=>k in pub);assert.equal(publicKeys.length,37);for(const k of lessonKeys){assert.ok(k in es,`missing full Spanish translation: ${k}`);assert.doesNotMatch(es[k],/[А-Яа-яЁё]/u,k)}for(const k of publicKeys)assert.equal(pub[k],es[k],k)});
test('Lesson 15 Spanish contains no known machine-translation residue',()=>{const forbidden=/Diágeno|Dative|Localizaciones|rogar la lista|Check-player|Restaurante Historia|tres pasillos|\b(?:cheese|salad|dessert)\b|Comproba, por|LATE\?|AFTER EDUCATION|satélite|finalismo|auto-testing|subjetivo-materia|restaurante-orden|denial van|\b(?:RolePlay|score|evidence|model answer|Controlled Practice|productos de código abierto)\b/iu;const failures=[...lessonKeys].map(k=>[k,es[k]]as const).filter(([,v])=>forbidden.test(v));assert.deepEqual(failures,[])});
test('Lesson 15 Spanish preserves datives, possession, absence, and food preference',()=>{assert.match(es['Сначала найди адресата, затем задай Kinek? и только после этого выбери -nak или -nek по гармонии гласных.'],/destinatario.*Kinek\?.*-nak o -nek.*armonía/u);assert.match(es['Не строй формы как *énnek, *tenek или *őnek. Для личных местоимений используются специальные формы: nekem, neked, neki...'],/formas especiales: nekem, neked, neki/u);assert.match(es['Главная ошибка: оставить предмет без притяжательного суффикса. Не *Nekem van egy autó, а Nekem van egy autóm.'],/sin sufijo posesivo.*Nekem van egy autóm/u);assert.match(es['В обычном отрицании существования, наличия и обладания вместо *nem van используем nincs; для нескольких предметов — nincsenek.'],/nincs.*\*nem van.*nincsenek/u);assert.match(es['Szeretem a gulyáslevest. — люблю / мне вообще нравится гуляшевый суп (gulyáslevest — винительный падеж, объект). Nekem ízlik a gulyásleves. — гуляшевый суп нравится мне на вкус (gulyásleves — подлежащее, nekem — experiencer). Nem ízlik nekem a hal. — рыба мне не по вкусу.'],/acusativo.*objeto.*sujeto.*no me gusta el pescado/u);assert.equal(es['УРОК 15 · 9/11 · ПИСЬМО'],'LECCIÓN 15 · 9/11 · ESCRITURA')});
