import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import test from 'node:test';
import { LESSONS_META } from '../src/data/lessons/index.ts';
import { LESSON_9 } from '../src/data/lessons/lesson9.ts';
import type { ActivityEvidence, LessonActivity, ProseReadingContent } from '../src/types.ts';
import { describeExitCheckStatus, rolePlayCompletionEvidence, validateActivity, validateExitCheckReferences, validateLessonQuestionIds, writingEvidence } from '../src/utils/activityUtils.ts';

const activities=LESSON_9.slides.flatMap((slide)=>slide.activities??[]);const source=readFileSync(new URL('../src/data/lessons/lesson9.ts',import.meta.url),'utf8');
function find<K extends LessonActivity['kind']>(id:string,kind:K):Extract<LessonActivity,{kind:K}>{const activity=activities.find((candidate)=>candidate.id===id);assert.ok(activity,`missing ${id}`);assert.equal(activity.kind,kind);return activity as Extract<LessonActivity,{kind:K}>;}
function prose(reading:Extract<LessonActivity,{kind:'reading'}>):ProseReadingContent{assert.ok(reading.content);assert.equal(reading.content.type,'prose');if(reading.content.type!=='prose')assert.fail();return reading.content;}
const direct=(activityId:string):ActivityEvidence=>({activityId,attempted:true,completed:true,passed:true,evidenceMode:'direct'});

test('L9 preserves identity, objective IDs, quiz IDs, vocabulary IDs, and eleven slides',()=>{assert.deepEqual([LESSON_9.id,LESSON_9.number,LESSON_9.level,LESSON_9.slidesCount,LESSON_9.slides.length],[9,9,'A1',11,11]);assert.deepEqual(LESSON_9.slides.map((slide)=>slide.id),[1,2,3,4,5,6,7,8,9,10,11]);assert.deepEqual(LESSON_9.objectives?.map((o)=>o.id),['l9_use-adjectives','l9_form-comparative','l9_form-superlative','l9_use-mint','l9_compare-people']);assert.deepEqual(LESSON_9.quiz?.map((q)=>q.id),[901,902,903,904,905,906]);assert.deepEqual(LESSON_9.vocabulary?.map((v)=>v.id),Array.from({length:16},(_,i)=>`l9_v${i+1}`));for(let slide=1;slide<=11;slide+=1)assert.equal(existsSync(new URL(`../public/audio/9.${slide}.mp3`,import.meta.url)),true);});

test('L9 exposes its intentional no-Listening communication sequence and valid ExitCheck',()=>{assert.deepEqual(activities.map((a)=>a.kind),['controlledPractice','reading','rolePlay','writing','exitCheck']);assert.deepEqual(activities.flatMap(validateActivity),[]);assert.deepEqual(validateLessonQuestionIds(activities),[]);assert.equal(activities.some((a)=>a.kind==='listening'),false);assert.equal(existsSync(new URL('../public/audio/l9_listening_context.mp3',import.meta.url)),false);const exit=find('l9-exit-check','exitCheck');assert.deepEqual(validateExitCheckReferences(exit,LESSON_9.objectives?.map((o)=>o.id)??[],activities.map((a)=>a.id)),[]);assert.match(source,/В L9 намеренно нет learner-facing Listening и отдельного MP3/);});

test('L9 controlled practice has fourteen contextual items at 11/14 with meaning-led coverage',()=>{const cp=find('l9-cp-comparative-forms','controlledPractice');assert.deepEqual([cp.exercises.length,cp.passCount],[14,11]);const text=JSON.stringify(cp);for(const token of ['olcsó ↔ drága','nagyobb','kisebb','jobb','szebb','mint az A lakás','gyorsabb','Nekem a kisebb tetszik','mert olcsóbb','legjobb választás','zaj'] )assert.ok(text.includes(token),token);assert.ok(cp.exercises.filter((e)=>e.kind==='singleChoice').length>=7);});

test('L9 Reading is a 150–180 word apartment comparison with eight meaning questions',()=>{const reading=find('l9-reading-apartments','reading');const content=prose(reading);const words=content.paragraphs.join(' ').trim().split(/\s+/u).length;assert.ok(words>=150&&words<=180,`words=${words}`);assert.deepEqual([reading.questions.length,reading.passCount],[8,6]);assert.match(content.title??'',/Melyik lakás jobb/);const text=content.paragraphs.join(' ');for(const token of ['A lakás','B lakás','metró','busz','zajos','Dávid'])assert.ok(text.includes(token),token);});

test('L9 apartment RolePlay has eight learner turns, reacts to a drawback, and stays PARTIAL',()=>{const rolePlay=find('l9-roleplay-apartment-choice','rolePlay');assert.deepEqual([rolePlay.turns.length,rolePlay.turns.filter((t)=>t.speaker==='learner').length],[17,8]);assert.ok(rolePlay.turns.filter((t)=>t.speaker==='learner').every((t)=>t.responseMode==='selfPractice'));assert.match(JSON.stringify(rolePlay),/Melyik lakás.*nagyobb.*olcsóbb.*hátrány.*választ/s);assert.equal(rolePlayCompletionEvidence(rolePlay.id).evidenceMode,'partial');});

test('L9 Writing is 70–90 words while optional Speaking is text-only and non-evidentiary',()=>{const writing=find('l9-writing-comparison','writing');const words=writing.modelAnswer.join(' ').trim().split(/\s+/u).length;assert.ok(words>=70&&words<=90,`words=${words}`);assert.match(writing.prompt,/70–90 слов/);assert.equal(writingEvidence(writing.modelAnswer.join(' '),true).evidenceMode,'partial');const speaking=LESSON_9.slides.find((slide)=>slide.optionalSpeaking)?.optionalSpeaking;assert.ok(speaking);assert.match(speaking.instructions,/1–1\.5 минуты.*без микрофона.*score.*evidence/s);assert.doesNotMatch(source,/SpeechSynthesis|speechSynthesis|AudioRecorder|RecordingTask|MediaRecorder|getUserMedia|kind:\s*['"]recording/i);});

test('L9 ExitCheck keeps constrained grammar DIRECT and connected comparison PARTIAL',()=>{const exit=find('l9-exit-check','exitCheck');const evidence:Record<string,ActivityEvidence>={'l9-cp-comparative-forms':direct('l9-cp-comparative-forms'),'l9-reading-apartments':direct('l9-reading-apartments'),'l9-roleplay-apartment-choice':rolePlayCompletionEvidence('l9-roleplay-apartment-choice'),'l9-writing-comparison':{activityId:'l9-writing-comparison',attempted:true,selfReviewed:true,...writingEvidence('A sufficiently developed apartment comparison for review.',true)}};assert.deepEqual(Object.fromEntries(exit.checks.map((c)=>[c.objectiveId,describeExitCheckStatus(c,evidence[c.activityId],evidence).kind])),{'l9_use-adjectives':'direct-met','l9_form-comparative':'direct-met','l9_form-superlative':'direct-met','l9_use-mint':'direct-met','l9_compare-people':'partial-review'});});

test('L9 keeps predicate plural optional, avoids fake audio fallback, and aligns metadata',()=>{const optional=LESSON_9.slides.find((slide)=>slide.id===10);assert.ok(optional);assert.match(optional.body??'',/только для распознавания.*A házak nagyok/s);assert.doesNotMatch(JSON.stringify(activities),/A házak nagyok/);assert.doesNotMatch(JSON.stringify(LESSON_9.quiz),/A házak nagyok/);assert.match(optional.body??'',/Narration, word audio и browser TTS не используются как замена/);const meta=LESSONS_META.find((item)=>item.id===9);assert.ok(meta);assert.equal(meta.description,LESSON_9.description);assert.equal(meta.slidesCount,11);});
