import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import test from 'node:test';
import { LESSON_TRANSLATION_MAP } from '../src/data/lessonTranslations.ts';
import { LESSONS_META } from '../src/data/lessons/index.ts';
import { LESSON_8 } from '../src/data/lessons/lesson8.ts';
import type { ActivityEvidence, LessonActivity, ProseReadingContent } from '../src/types.ts';
import { describeExitCheckStatus, listeningEvidence, rolePlayCompletionEvidence, validateActivity, validateExitCheckReferences, validateLessonQuestionIds, writingEvidence } from '../src/utils/activityUtils.ts';

const activities=LESSON_8.slides.flatMap((slide)=>slide.activities??[]);const source=readFileSync(new URL('../src/data/lessons/lesson8.ts',import.meta.url),'utf8');
function find<K extends LessonActivity['kind']>(id:string,kind:K):Extract<LessonActivity,{kind:K}>{const activity=activities.find((candidate)=>candidate.id===id);assert.ok(activity,`missing ${id}`);assert.equal(activity.kind,kind);return activity as Extract<LessonActivity,{kind:K}>;}
function prose(reading:Extract<LessonActivity,{kind:'reading'}>):ProseReadingContent{assert.ok(reading.content);assert.equal(reading.content.type,'prose');if(reading.content.type!=='prose')assert.fail();return reading.content;}
const direct=(activityId:string):ActivityEvidence=>({activityId,attempted:true,completed:true,passed:true,evidenceMode:'direct'});

test('L8 preserves identity, objective IDs, quiz IDs, vocabulary IDs, and eleven slides',()=>{assert.deepEqual([LESSON_8.id,LESSON_8.number,LESSON_8.level,LESSON_8.slidesCount,LESSON_8.slides.length],[8,8,'A1',11,11]);assert.deepEqual(LESSON_8.slides.map((slide)=>slide.id),[1,2,3,4,5,6,7,8,9,10,11]);assert.deepEqual(LESSON_8.objectives?.map((o)=>o.id),['l8_name-family','l8_form-possessive','l8_use-possessive','l8_distinguish-possessors','l8_describe-family']);assert.deepEqual(LESSON_8.quiz?.map((q)=>q.id),[801,802,803,804,805,806]);assert.deepEqual(LESSON_8.vocabulary?.map((v)=>v.id),Array.from({length:10},(_,i)=>`l8_v${i+1}`));for(let slide=1;slide<=11;slide+=1)assert.equal(existsSync(new URL(`../public/audio/8.${slide}.mp3`,import.meta.url)),true);});

test('L8 exposes the complete valid communication sequence and resolvable ExitCheck',()=>{assert.deepEqual(activities.map((a)=>a.kind),['controlledPractice','reading','listening','rolePlay','writing','exitCheck']);assert.deepEqual(activities.flatMap(validateActivity),[]);assert.deepEqual(validateLessonQuestionIds(activities),[]);const exit=find('l8-exit-check','exitCheck');assert.deepEqual(validateExitCheckReferences(exit,LESSON_8.objectives?.map((o)=>o.id)??[],activities.map((a)=>a.id)),[]);});

test('L8 practice has fourteen contextual family and singular-possession items at 11/14',()=>{const cp=find('l8-cp-singular-possessives','controlledPractice');assert.deepEqual([cp.exercises.length,cp.passCount],[14,11]);const text=JSON.stringify(cp);for(const token of ['testvér','Ez az anyukám','házam','házad','háza','Van egy testvérem','Nincs testvérem','Anyám tanár','Hol laknak a szüleid','Hány éves a fiad','Ez Anna könyve'])assert.ok(text.includes(token),token);});

test('L8 Reading is a 140–170 word family profile with seven meaning questions',()=>{const reading=find('l8-reading-family-profile','reading');const content=prose(reading);const words=content.paragraphs.join(' ').trim().split(/\s+/u).length;assert.ok(words>=140&&words<=170,`words=${words}`);assert.deepEqual([reading.questions.length,reading.passCount],[7,6]);assert.match(content.title??'',/Két család egy házban/);assert.match(content.paragraphs.join(' '),/Kovács család.*Anna.*szüleik.*szombaton.*együtt/s);});

test('L8 family RolePlay has eight learner turns, asks back, and remains PARTIAL',()=>{const rolePlay=find('l8-roleplay-family-talk','rolePlay');assert.deepEqual([rolePlay.turns.length,rolePlay.turns.filter((t)=>t.speaker==='learner').length],[17,8]);assert.ok(rolePlay.turns.filter((t)=>t.speaker==='learner').every((t)=>t.responseMode==='selfPractice'));assert.match(JSON.stringify(rolePlay),/Van testvéred.*Mi a testvéred neve.*Hol lakik.*szüleid.*És neked van testvéred/s);assert.equal(rolePlayCompletionEvidence(rolePlay.id).evidenceMode,'partial');});

test('L8 Writing is 60–80 words while optional Speaking is text-only and non-evidentiary',()=>{const writing=find('l8-writing-family-description','writing');const words=writing.modelAnswer.join(' ').trim().split(/\s+/u).length;assert.ok(words>=60&&words<=80,`words=${words}`);assert.match(writing.prompt,/60–80 слов/);assert.equal(writingEvidence(writing.modelAnswer.join(' '),true).evidenceMode,'partial');const speaking=LESSON_8.slides.find((slide)=>slide.optionalSpeaking)?.optionalSpeaking;assert.ok(speaking);assert.match(speaking.instructions,/1–1\.5 минуты.*без микрофона.*score.*evidence/s);assert.doesNotMatch(source,/SpeechSynthesis|speechSynthesis|AudioRecorder|RecordingTask|MediaRecorder|getUserMedia|kind:\s*['"]recording/i);});

test('L8 preserves the exact published Listening contract and MP3 hash',()=>{const listening=find('l8-listening-possessives','listening');assert.deepEqual([listening.assetId,listening.audioStatus,listening.questions.length,listening.passCount],['l8_listening_possessives','published',4,4]);assert.equal(listening.transcript,'Az én nevem Anna. Anyám tanár, apám orvos. Péter a testvérem. Péter háza nagy, az én házam kicsi. A te családod nagy?');assert.equal(createHash('sha256').update(readFileSync(new URL('../public/audio/l8_listening_possessives.mp3',import.meta.url))).digest('hex'),'77aaf4a84d20e4ef61419eb0535d6c31b2ab3c0079440ed6508c29451f70879e');assert.equal(listeningEvidence(listening,4,4,true).evidenceMode,'direct');assert.equal(listeningEvidence(listening,4,4,false).evidenceMode,'none');});

test('L8 ExitCheck keeps constrained work DIRECT and family production PARTIAL',()=>{const exit=find('l8-exit-check','exitCheck');const listening=find('l8-listening-possessives','listening');const evidence:Record<string,ActivityEvidence>={'l8-cp-singular-possessives':direct('l8-cp-singular-possessives'),'l8-listening-possessives':{activityId:'l8-listening-possessives',attempted:true,completed:true,...listeningEvidence(listening,4,4,true)},'l8-roleplay-family-talk':rolePlayCompletionEvidence('l8-roleplay-family-talk'),'l8-writing-family-description':{activityId:'l8-writing-family-description',attempted:true,selfReviewed:true,...writingEvidence('A sufficiently developed family description for review.',true)}};assert.deepEqual(Object.fromEntries(exit.checks.map((c)=>[c.objectiveId,describeExitCheckStatus(c,evidence[c.activityId],evidence).kind])),{'l8_name-family':'direct-met','l8_form-possessive':'direct-met','l8_use-possessive':'direct-met','l8_distinguish-possessors':'direct-met','l8_describe-family':'partial-review'});});

test('L8 remains bounded to singular ownership and metadata/translations stay aligned',()=>{assert.doesNotMatch(JSON.stringify(activities),/házaim|házaid|házai|házunk|házatok|házuk/);assert.match(LESSON_8.slides.find((slide)=>slide.id===11)?.body??'',/házaim.*необязательным распознаванием/s);const meta=LESSONS_META.find((item)=>item.id===8);assert.ok(meta);assert.equal(meta.description,LESSON_8.description);assert.equal(meta.slidesCount,11);assert.equal(LESSON_TRANSLATION_MAP[8]?.[1]?.targetText,'Van egy testvérem.');});
