import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { buildVocabularyPlan } from './vocabularyPlan';
import {
  INTENTIONAL_ORPHAN_REVIEW_CARD_IDS,
  LEGACY_REVIEW_CARD_ALIASES,
} from '../src/data/vocabularyLegacy';

const root = resolve(import.meta.dirname, '..');
const generatedPath = resolve(root, 'src/data/generatedVocabularyCatalog.ts');
const inventoryPath = resolve(root, 'docs/vocabulary-inventory.json');
const auditPath = resolve(root, 'docs/VOCABULARY_AUDIT.md');

const plan = await buildVocabularyPlan();
const cardByLexeme = new Map(plan.cards.map((card) => [card.lexemeId, card]));

const generated = `// Generated by npm run export:vocabulary. Do not edit by hand.
import type { VocabularyCard, VocabularyInventoryEntry, VocabularyLexeme } from '../types';

export const GENERATED_VOCABULARY_ENTRIES = ${JSON.stringify(plan.entries, null, 2)} as VocabularyInventoryEntry[];
export const GENERATED_VOCABULARY_LEXEMES = ${JSON.stringify(plan.lexemes, null, 2)} as VocabularyLexeme[];
export const GENERATED_VOCABULARY_CARDS = ${JSON.stringify(plan.cards, null, 2)} as VocabularyCard[];
export const GENERATED_VOCABULARY_LESSON_SUMMARIES = ${JSON.stringify(plan.lessons, null, 2)} as const;
`;

const inventory = {
  generatedFrom: 'src/data/lessons/lesson1.ts … lesson28.ts (lesson.vocabulary) + explicit metadata in src/data/vocabularyConfig.ts',
  totals: {
    targetVocabularyEntries: plan.entries.length,
    uniqueLexemes: plan.lexemes.length,
    srsEligibleCards: plan.cards.length,
    excludedFromSrs: plan.exclusions.length,
    recycledLexemes: plan.recycled.length,
    legacyAliases: Object.keys(LEGACY_REVIEW_CARD_ALIASES).length,
    intentionalOrphanLegacyCards: INTENTIONAL_ORPHAN_REVIEW_CARD_IDS.length,
  },
  lessons: plan.lessons,
  lexemes: plan.lexemes.map((lexeme) => ({
    ...lexeme,
    cardId: cardByLexeme.get(lexeme.id)?.id ?? null,
    srsEligible: cardByLexeme.has(lexeme.id),
  })),
  entries: plan.entries,
  legacyReviewCardAliases: LEGACY_REVIEW_CARD_ALIASES,
  intentionalOrphanReviewCardIds: INTENTIONAL_ORPHAN_REVIEW_CARD_IDS,
  qaFlags: plan.qaFlags,
};

const lessonRows = plan.lessons
  .map((lesson) => `| L${lesson.lesson} | ${lesson.target} | ${lesson.newLexemes} | ${lesson.recycledLexemes} | ${lesson.srsEligible} | ${lesson.excluded} |`)
  .join('\n');
const resolvedGroups = plan.lexemes
  .filter((lexeme) => lexeme.forms.length > 1 || lexeme.usedInLessons.length > 1)
  .map((lexeme) => `- **${lexeme.lemma}** (${lexeme.id}): forms ${lexeme.forms.join(', ')}; introduced L${lexeme.lessonIntroduced}; used L${lexeme.usedInLessons.join(', L')}.`)
  .join('\n');
const exclusions = plan.exclusions
  .map((entry) => `- L${entry.lessonNumber} **${entry.hu}** (${entry.id}): ${entry.srsExclusionReason}`)
  .join('\n');
const qaFlags = plan.qaFlags.map((flag) => `- ${flag}`).join('\n');

const audit = `# Vocabulary audit

Generated from lesson source data. “SRS” in the lesson table means distinct eligible lexemes targeted in that lesson; the course total counts unique review cards.

## Course totals

- Target vocabulary entries: ${plan.entries.length}
- Unique lexemes: ${plan.lexemes.length}
- SRS cards: ${plan.cards.length}
- Excluded entries: ${plan.exclusions.length}
- Recycled lexemes: ${plan.recycled.length}
- Legacy aliases: ${Object.keys(LEGACY_REVIEW_CARD_ALIASES).length}
- Intentional orphan legacy cards: ${INTENTIONAL_ORPHAN_REVIEW_CARD_IDS.length}

## By lesson

| Lesson | Target | New | Recycled | SRS | Excluded |
|---:|---:|---:|---:|---:|---:|
${lessonRows}

## Duplicate / lemma resolution

${resolvedGroups || '- None.'}

## Exclusions

${exclusions || '- None.'}

## Recycled vocabulary

${plan.recycled.map((lexeme) => `- **${lexeme.lemma}**: introduced L${lexeme.lessonIntroduced}; reused L${lexeme.usedInLessons.filter((lesson) => lesson !== lexeme.lessonIntroduced).join(', L')}.`).join('\n') || '- None.'}

## Backward compatibility

Old persisted review states are not rewritten or deleted. ${Object.keys(LEGACY_REVIEW_CARD_ALIASES).length} legacy IDs resolve to current cards. ${INTENTIONAL_ORPHAN_REVIEW_CARD_IDS.length} IDs that no longer belong to target vocabulary are retained as orphan state and ignored by due-card UI.

## QA flags

${qaFlags}
`;

await Promise.all([
  writeFile(generatedPath, generated, 'utf8'),
  writeFile(inventoryPath, `${JSON.stringify(inventory, null, 2)}\n`, 'utf8'),
  writeFile(auditPath, audit, 'utf8'),
]);

console.log(`Vocabulary export complete: ${plan.entries.length} entries, ${plan.lexemes.length} lexemes, ${plan.cards.length} SRS cards.`);
