import fs from 'fs';
import path from 'path';

const audioDir = path.resolve('public/audio');
const manifestPath = path.resolve('src/data/slideAudioManifest.ts');

if (!fs.existsSync(audioDir)) {
  fs.mkdirSync(audioDir, { recursive: true });
}

const files = fs.readdirSync(audioDir);
const slidePattern = /^(\d+)\.(\d+)\.mp3$/;

const counts: Record<number, number> = {};
const presentFiles: Record<string, boolean> = {};

for (const file of files) {
  const match = file.match(slidePattern);
  if (match) {
    const lesson = parseInt(match[1], 10);
    const slide = parseInt(match[2], 10);

    if (!counts[lesson] || slide > counts[lesson]) {
      counts[lesson] = Math.max(counts[lesson] || 0, slide);
    }

    presentFiles[`${lesson}.${slide}`] = true;
    presentFiles[`l${lesson}_s${slide}`] = true;
  }
}

const fileContent = `// Auto-generated by scripts/generate-audio-manifest.ts - DO NOT EDIT MANUALLY

export const SLIDE_AUDIO_COUNTS: Record<number, number> = ${JSON.stringify(counts, null, 2)};

export const PRESENT_SLIDE_AUDIO: Record<string, boolean> = ${JSON.stringify(presentFiles, null, 2)};
`;

fs.writeFileSync(manifestPath, fileContent, 'utf-8');
console.log(`[Audio Manifest] Generated ${manifestPath} successfully with ${Object.keys(presentFiles).length / 2} slide files across ${Object.keys(counts).length} lessons.`);
