import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { LESSONS_META, loadLesson } from '../src/data/lessons/index';
import { getRequiredLessonProgressUnits, type LessonProgressDefinition } from '../src/utils/lessonProgress';

export async function buildLessonProgressDefinitions(): Promise<LessonProgressDefinition[]> {
  const definitions: LessonProgressDefinition[] = [];
  const allActivityOwner = new Map<string, number>();
  for (const meta of LESSONS_META) {
    const lesson = await loadLesson(meta.number, { admin: true });
    if (!lesson) throw new Error(`Lesson ${meta.number} could not be loaded.`);
    for (const slide of lesson.slides) {
      for (const activity of slide.activities ?? []) {
        const owner = allActivityOwner.get(activity.id);
        if (owner !== undefined) {
          throw new Error(`Duplicate lesson activity id ${activity.id} in lessons ${owner} and ${lesson.number}`);
        }
        allActivityOwner.set(activity.id, lesson.number);
      }
    }
    const units = getRequiredLessonProgressUnits(lesson);
    definitions.push({
      lessonNumber: lesson.number,
      quizRequired: (lesson.quiz?.length ?? 0) > 0,
      quizTotal: lesson.quiz?.length ?? 0,
      quizPassCount: lesson.quiz?.length ? Math.ceil(lesson.quiz.length * 0.8) : 0,
      units,
    });
  }
  assertUniqueProgressUnitIds(definitions);
  return definitions;
}

export function assertUniqueProgressUnitIds(definitions: readonly LessonProgressDefinition[]): void {
  const globalActivityOwner = new Map<string, number>();
  for (const definition of definitions) {
    for (const unit of definition.units) {
      const owner = globalActivityOwner.get(unit.activityId);
      if (owner !== undefined) {
        throw new Error(`Duplicate progress activity id ${unit.activityId} in lessons ${owner} and ${definition.lessonNumber}`);
      }
      if (unit.activityId === `quiz:${definition.lessonNumber}`) {
        throw new Error(`Activity id ${unit.activityId} conflicts with the lesson quiz unit.`);
      }
      globalActivityOwner.set(unit.activityId, definition.lessonNumber);
    }
  }
}

export function renderLessonProgressCatalog(definitions: readonly LessonProgressDefinition[]): string {
  return `// Auto-generated by scripts/generate-lesson-progress-catalog.ts - DO NOT EDIT MANUALLY\n\nimport type { LessonProgressDefinition } from '../utils/lessonProgress';\n\nexport const LESSON_PROGRESS_DEFINITIONS: readonly LessonProgressDefinition[] = ${JSON.stringify(definitions, null, 2)};\n`;
}

export function assertLessonProgressCatalogCurrent(current: string, expected: string): void {
  if (current !== expected) throw new Error('Lesson progress catalog is stale. Run npm run generate:progress.');
}

export async function generateLessonProgressCatalog(checkOnly = false): Promise<void> {
  const definitions = await buildLessonProgressDefinitions();
  const target = path.resolve('src/data/lessonProgressCatalog.ts');
  const source = renderLessonProgressCatalog(definitions);
  if (checkOnly) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
    assertLessonProgressCatalogCurrent(current, source);
    console.log(`Lesson progress catalog is current: ${definitions.length} lessons, ${definitions.reduce((sum, item) => sum + item.units.length, 0)} required activities.`);
    return;
  }
  fs.writeFileSync(target, source, 'utf8');
  console.log(`Lesson progress catalog generated: ${definitions.length} lessons, ${definitions.reduce((sum, item) => sum + item.units.length, 0)} required activities.`);
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (import.meta.url === invokedPath) {
  await generateLessonProgressCatalog(process.argv.includes('--check'));
}
