import fs from 'fs';
import path from 'path';
import { createHash } from 'crypto';

const audioDir = path.resolve('public/audio/narration/es');
const manifestPath = path.resolve('src/data/spanishNarrationManifest.ts');
const slidePattern = /^(\d+)\.(\d+)\.mp3$/;

if (!fs.existsSync(audioDir)) {
  throw new Error(`Spanish narration directory is missing: ${audioDir}`);
}

const versions: Record<string, string> = {};
for (const file of fs.readdirSync(audioDir)) {
  if (!file.endsWith('.mp3')) continue;
  if (!slidePattern.test(file)) {
    throw new Error(`Unexpected Spanish narration filename: ${file}`);
  }
  const key = file.slice(0, -4);
  const contents = fs.readFileSync(path.join(audioDir, file));
  if (contents.length === 0) {
    throw new Error(`Empty Spanish narration file: ${file}`);
  }
  versions[key] = createHash('sha256').update(contents).digest('hex').slice(0, 12);
}

const fileContent = `// Auto-generated by scripts/generate-spanish-narration-manifest.ts - DO NOT EDIT MANUALLY

// Every key represents an existing public/audio/narration/es/<lesson>.<slide>.mp3.
// Content hashes invalidate browser/CDN caches when a recording is replaced.
export const SPANISH_NARRATION_VERSIONS: Record<string, string> = ${JSON.stringify(versions, null, 2)};
`;

fs.writeFileSync(manifestPath, fileContent, 'utf-8');
console.log(`[Audio Manifest] Generated ${manifestPath} with ${Object.keys(versions).length} Spanish narration files.`);
