// Auto-generated by scripts/generate-lesson-progress-catalog.ts - DO NOT EDIT MANUALLY

import type { LessonProgressDefinition } from '../utils/lessonProgress';

export const LESSON_PROGRESS_DEFINITIONS: readonly LessonProgressDefinition[] = [
  {
    "lessonNumber": 1,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l1-listening-vowel-length",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l1-cp-vowel-spelling",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 10,
        "total": 12
      },
      {
        "activityId": "l1-listening-soft-consonants",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l1-cp-consonant-graphemes",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 7,
        "total": 8
      },
      {
        "activityId": "l1-listening-s-sz",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l1-cp-s-sz-reading",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l1-cp-stress-rule",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 5,
        "total": 5
      },
      {
        "activityId": "l1-cp-foundation-discrimination",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 13,
        "total": 16
      },
      {
        "activityId": "l1-reading-decoding",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l1-writing-first-forms",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 2,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l2-cp-pronoun-referents",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l2-cp-pronoun-context",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l2-cp-lenni",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 6,
        "total": 6
      },
      {
        "activityId": "l2-cp-contextual-foundation",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l2-listening-introduction",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l2-reading-first-meeting",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l2-roleplay-first-meeting",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l2-roleplay-greetings",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l2-writing-fictional-introduction",
        "kind": "writing",
        "requirement": "complete"
      },
      {
        "activityId": "l2-writing-self-introduction",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 3,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l3-cp-articles",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 10,
        "total": 14
      },
      {
        "activityId": "l3-cp-egy",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l3-cp-plurals",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l3-reading-classroom",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l3-roleplay-classroom-objects",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l3-reading-room",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l3-cp-contextual-foundation",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l3-writing-fictional-room",
        "kind": "writing",
        "requirement": "complete"
      },
      {
        "activityId": "l3-cp-written-phrases",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l3-writing-room",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 4,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l4-cp-recognize-text",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l4-cp-conjugation",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l4-cp-negation",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l4-reading-simple-day",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l4-listening-present-forms",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l4-cp-questions",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l4-cp-contextual-foundation",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 12,
        "total": 15
      },
      {
        "activityId": "l4-roleplay-simple-day",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l4-writing-fictional-day",
        "kind": "writing",
        "requirement": "complete"
      },
      {
        "activityId": "l4-cp-context",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l4-writing-actions",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 5,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l5-cp-number-recognition",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l5-cp-write-numbers",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l5-cp-weekday-order",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 7,
        "total": 7
      },
      {
        "activityId": "l5-cp-month-order",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 10,
        "total": 12
      },
      {
        "activityId": "l5-reading-weekly-program",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l5-reading-weekly-schedule",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l5-listening-number-dictation",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l5-listening-time-schedule",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l5-roleplay-arrange-meeting",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l5-roleplay-schedule",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l5-cp-contextual-foundation",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 13,
        "total": 16
      },
      {
        "activityId": "l5-writing-weekly-message",
        "kind": "writing",
        "requirement": "complete"
      },
      {
        "activityId": "l5-writing-schedule",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 6,
    "quizRequired": true,
    "quizTotal": 8,
    "quizPassCount": 7,
    "units": [
      {
        "activityId": "l6-reading-new-course-day",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 7,
        "total": 8
      },
      {
        "activityId": "l6-reading-a0-profile",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l6-cp-decoding",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l6-cp-a0-functions",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l6-cp-plural-articles",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l6-cp-present-verbs",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 8,
        "total": 10
      },
      {
        "activityId": "l6-listening-a0-review",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l6-roleplay-first-course-day",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l6-roleplay-schedule",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l6-writing-integrated-profile",
        "kind": "writing",
        "requirement": "complete"
      },
      {
        "activityId": "l6-writing-profile",
        "kind": "writing",
        "requirement": "complete"
      },
      {
        "activityId": "l6-cp-integrated-checkpoint",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 15,
        "total": 18
      }
    ]
  },
  {
    "lessonNumber": 7,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l7-cp-accusative-forms",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l7-reading-bookshop",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l7-listening-accusative",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l7-roleplay-shop",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l7-writing-shopping-note",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 8,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l8-cp-singular-possessives",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l8-reading-family-profile",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l8-listening-possessives",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 4
      },
      {
        "activityId": "l8-roleplay-family-talk",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l8-writing-family-description",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 9,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l9-cp-comparative-forms",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l9-reading-apartments",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l9-roleplay-apartment-choice",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l9-writing-comparison",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 10,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l10-cp-meaning",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l10-reading-dialogue",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l10-listening-inner-locations",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l10-roleplay-meeting-place",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l10-writing-morning-route",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 11,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l11-cp-meaning-family",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l11-reading-budapest-route",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l11-roleplay-town-route",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l11-writing-city-route",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 12,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l12-cp-near-meanings",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l12-reading-library-route",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l12-listening-near-locations",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l12-roleplay-public-route",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l12-writing-near-exchange",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 13,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l13-cp-past-forms",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l13-reading-tense-contrast",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l13-listening-tense-contrast",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l13-roleplay-weekend",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l13-writing-past-story",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 14,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l14-cp-routine-forms",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 13,
        "total": 16
      },
      {
        "activityId": "l14-reading-daily-routine",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l14-listening-routine",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l14-roleplay-routine-comparison",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l14-writing-daily-routine",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 15,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l15-cp-dative",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l15-reading-menu",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l15-listening-restaurant",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 3,
        "total": 4
      },
      {
        "activityId": "l15-roleplay-restaurant",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l15-writing-preferences",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 16,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l16-cp-contextual-shopping",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l16-reading-jacket-exchange",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l16-listening-shopping",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 3,
        "total": 4
      },
      {
        "activityId": "l16-roleplay-shopping",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l16-writing-exchange-message",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 17,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l17-cp-contextual-weather",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l17-reading-weekend-weather",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l17-listening-weather",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l17-roleplay-weather-plan",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l17-writing-weekend-plan",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 18,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l18-cp-contextual-modals",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l18-reading-first-day",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l18-listening-modals",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l18-roleplay-course-rules",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l18-writing-modal-responses",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 19,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l19-cp-contextual-future",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l19-reading-busy-weekend",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l19-listening-future",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l19-roleplay-saturday-plan",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l19-writing-plans-predictions",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 20,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l20-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 13,
        "total": 16
      },
      {
        "activityId": "l20-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l20-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l20-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l20-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 21,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l21-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 9,
        "total": 12
      },
      {
        "activityId": "l21-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l21-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l21-listening-b-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l21-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l21-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 22,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l22-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 9,
        "total": 12
      },
      {
        "activityId": "l22-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l22-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l22-listening-b-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l22-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l22-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 23,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l23-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 9,
        "total": 12
      },
      {
        "activityId": "l23-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 5,
        "total": 6
      },
      {
        "activityId": "l23-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l23-listening-b-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l23-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l23-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 24,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l24-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l24-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l24-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l24-listening-b-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 6,
        "total": 7
      },
      {
        "activityId": "l24-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l24-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 25,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l25-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l25-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 10,
        "total": 13
      },
      {
        "activityId": "l25-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l25-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l25-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 26,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l26-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l26-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 10,
        "total": 13
      },
      {
        "activityId": "l26-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l26-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l26-roleplay-interaction-2",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l26-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 27,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l27-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 6,
        "total": 8
      },
      {
        "activityId": "l27-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 11,
        "total": 14
      },
      {
        "activityId": "l27-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l27-roleplay-interaction",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l27-roleplay-interaction-2",
        "kind": "rolePlay",
        "requirement": "complete"
      },
      {
        "activityId": "l27-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  },
  {
    "lessonNumber": 28,
    "quizRequired": true,
    "quizTotal": 6,
    "quizPassCount": 5,
    "units": [
      {
        "activityId": "l28-cp-core",
        "kind": "controlledPractice",
        "requirement": "pass",
        "passCount": 4,
        "total": 5
      },
      {
        "activityId": "l28-reading-context",
        "kind": "reading",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l28-listening-context",
        "kind": "listening",
        "requirement": "pass",
        "passCount": 2,
        "total": 3
      },
      {
        "activityId": "l28-writing-production",
        "kind": "writing",
        "requirement": "complete"
      }
    ]
  }
];
